language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - curl --silent http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction --prefer-source

script: phpunit --coverage-text --colors

notifications:
  email:
    - tim+build@nagel.com.au
